# Generated by Django 4.1.1 on 2023-03-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_post_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postm',
        ),
    ]
